# Welcome to Jekyll!
#

# Site settings
title: Start2Scale.io
description: |
 Startup Growth Consulting
owner: Adam Schneider # or company name
first_published: 2017 # if migrating another site, the year of your first publish
email: adam@start2scale.io
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://theenigmatict.github.io" # the base hostname & protocol for your site
social:
  twitter: https://twitter.com/adamschnieder
  linkedin-square: https://linkedin.com/in/adamschnieder
  email: adam@start2scale.io
  #flickr:
  #instagram:
  #youtube-square:
  #spotify:
  #stack-overflow:
  #vimeo:
  #stmubleupon:
  #delicious:
  #pied-piper:
  #digg:
  #soundcloud:
  #deviantart:
  #angellist:
  #tumblr-square:
  #stackexchange:
  #weibo:
  #trello:
  #foursquare:
  #linux:
  #bitbucket-square:
  #vk:
  #slack:
  #vine:
  #weixin:
  #yelp:
  #skyatlas:
  #leanpub:
  #connectdevelop:
  #ils:
  #forumbee:
  #tripadvisor:
  #amazon:

# Build settings
markdown: kramdown
#sass:
#  style: compressed
